name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  publish_package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Add profile credentials to ~/.aws/credentials
        run: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID --profile devops
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY --profile devops
            aws configure set default.region us-east-1 --profile devops

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install pipenv
        run: pip install pipenv

      - name: Install toml and tomli
        run: pipenv install tomli toml

      - name: Minor version bump
        run: pipenv run bash ./scripts/bump_version.sh
      
      - name: Commit version bump
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add src/dkany/__about__.py
          git commit -m "Bump version $(cat src/dkany/__about__.py | grep '__version__' | cut -d'=' -f2)"
          
      # Optional: Push the commit to the main branch
      # This step might not be required if you're just making the commit and not pushing it
      - name: Push changes
        run: |
          git push -u origin HEAD

      # # # TODO: Figure out running the package version bump in hatch, commiting it, and tagging it, from here
      # - name: Deploy
      #   run: pipenv run bash ./scripts/publish_package.sh